Added workingDirectory

diff --git a/azuretf/simpletf/azure-pipelines.yml b/azuretf/simpletf/azure-pipelines.yml
--- a/azuretf/simpletf/azure-pipelines.yml
+++ b/azuretf/simpletf/azure-pipelines.yml
@@ -107,21 +107,21 @@ stages:
     # -----------------------------
     # Ensure jq is installed
     # -----------------------------
-    - script: |
-        echo "Checking jq installation..."
-        if command -v jq >/dev/null 2>&1; then
-          echo "jq already installed: $(jq --version)"
-        else
-          echo "jq not found. Installing jq..."
-          if command -v yum >/dev/null 2>&1; then
-            sudo yum install -y jq
-          else
-            echo "ERROR: Unsupported package manager. Install jq manually."
-            exit 1
-          fi
-          echo "jq installed successfully: $(jq --version)"
-        fi
-      displayName: "Ensure jq is installed"
+    #- script: |
+    #    echo "Checking jq installation..."
+    #    if command -v jq >/dev/null 2>&1; then
+    #      echo "jq already installed: $(jq --version)"
+    #    else
+    #      echo "jq not found. Installing jq..."
+    #      if command -v yum >/dev/null 2>&1; then
+    #        sudo yum install -y jq
+    #      else
+    #        echo "ERROR: Unsupported package manager. Install jq manually."
+    #        exit 1
+    #      fi
+    #      echo "jq installed successfully: $(jq --version)"
+    #    fi
+    #  displayName: "Ensure jq is installed"
       
     # -----------------------------
     # Make runterraform.sh executable
@@ -249,6 +249,7 @@ stages:
     - script: |
           chmod +x ./pushlogs.sh
           ./pushlogs.sh
+      workingDirectory: azuretf/simpletf
       displayName: "Commit Terraform Logs"
       condition: always()
       env:
